import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';

import '@/app/globals.css';
import NextAuthWrapper from "@/library/next.auth.wrapper";
import { AppContextProvider } from "@/library/contexts/app.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@nguyenthaisonny",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <NextAuthWrapper>
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </NextAuthWrapper>
        </AppContextProvider>

      </body>
    </html>
  );
}
